-- Create table for repair line items
CREATE TABLE IF NOT EXISTS riwayat_perbaikan_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  perbaikan_id INT NOT NULL,
  nama_barang VARCHAR(150) NOT NULL,
  qty DECIMAL(12,2) NOT NULL DEFAULT 0,
  satuan VARCHAR(32) DEFAULT NULL,
  harga DECIMAL(15,2) NOT NULL DEFAULT 0,
  urutan INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_rp_items_rp FOREIGN KEY (perbaikan_id) REFERENCES riwayat_perbaikan(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
